# GENERATED FILE. DO NOT EDIT
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/ui")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} ui)
set(ui_path "/Users/vladas/.deps/ui")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/image")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} image)
set(image_path "/Users/vladas/.deps/image")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/scene")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} scene)
set(scene_path "/Users/vladas/.deps/scene")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/sprites")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} sprites)
set(sprites_path "/Users/vladas/.deps/sprites")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/geometry")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} geometry)
set(geometry_path "/Users/vladas/.deps/geometry")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/cpp_utils")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} cpp_utils)
set(cpp_utils_path "/Users/vladas/.deps/cpp_utils")
set(GIT_DEPENDENCIES_PATHS ${GIT_DEPENDENCIES_PATHS} "/Users/vladas/.deps/gl_wrapper")
set(GIT_DEPENDENCIES ${GIT_DEPENDENCIES} gl_wrapper)
set(gl_wrapper_path "/Users/vladas/.deps/gl_wrapper")
set(test_engine_path "/Users/vladas/.deps/test_engine")
set(CMAKE_UTILS_PATH ~/.deps/build_tools/utils.cmake)
set(DESKTOP_BUILD NO)
set(IOS_BUILD NO)
set(ANDROID_BUILD YES)
set(NEEDS_SIGNING YES)
add_definitions(-DNO_FREETYPE)
add_definitions(-DNO_ASSIMP)
add_definitions(-DNO_BOX2D)
add_definitions(-DNO_SOIL)
include(${CMAKE_UTILS_PATH})
set(BUILD_INFO conanbuildinfo.cmake)
set(NEEDS_CONAN NO)
